// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-aggVYEoUTNwTFF4dUOVCTR_czhHBuOA',
    appId: '1:727107509123:web:63491fdf6fca4568c0b4b6',
    messagingSenderId: '727107509123',
    projectId: 'taba-23679',
    authDomain: 'taba-23679.firebaseapp.com',
    storageBucket: 'taba-23679.appspot.com',
    measurementId: 'G-TKRXH00C06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg5YuBTHLemwjkZ7l3NThhSuQWQIBqy18',
    appId: '1:727107509123:android:e1256a06537922dbc0b4b6',
    messagingSenderId: '727107509123',
    projectId: 'taba-23679',
    storageBucket: 'taba-23679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6uoM_EsGM1-cRX4zP3oPOLtfVzaab9zI',
    appId: '1:727107509123:ios:d4198c47536e780dc0b4b6',
    messagingSenderId: '727107509123',
    projectId: 'taba-23679',
    storageBucket: 'taba-23679.appspot.com',
    iosClientId: '727107509123-ngqcv0me3v9u8c1ql8djsqfeqgoghusm.apps.googleusercontent.com',
    iosBundleId: 'com.example.taba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6uoM_EsGM1-cRX4zP3oPOLtfVzaab9zI',
    appId: '1:727107509123:ios:d4198c47536e780dc0b4b6',
    messagingSenderId: '727107509123',
    projectId: 'taba-23679',
    storageBucket: 'taba-23679.appspot.com',
    iosClientId: '727107509123-ngqcv0me3v9u8c1ql8djsqfeqgoghusm.apps.googleusercontent.com',
    iosBundleId: 'com.example.taba',
  );
}
